version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "17"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "shell"